# DataFrame

In [6]:
import pandas as pd
data={
    "Name":["Aftab","Ghaffar","Arslan","Abdullah"],
    "Age":[20,18,22,21],
    "Marks":[100,80,85,95]
}
df=pd.DataFrame(data)
print(df)

       Name  Age  Marks
0     Aftab   20    100
1   Ghaffar   18     80
2    Arslan   22     85
3  Abdullah   21     95

In [7]:
#Return row 0
import pandas as pd

data={
    "Name":["Aftab","Ghaffar","Arslan","Abdullah"],
    "Age":[20,18,22,21],
    "Marks":[100,80,85,95]   
}
df=pd.DataFrame(data)
print(df.loc[0])

Name     Aftab
Age         20
Marks      100
Name: 0, dtype: object

In [10]:
print(df.loc[[0,1]])

      Name  Age  Marks
0    Aftab   20    100
1  Ghaffar   18     80

In [15]:
import pandas as pd
data={
    "Name":["Aftab","Ghaffar","Arslan","Abdullah"],
    "Age":[20,18,22,21],
    "Marks":[100,80,85,95]
}
df=pd.DataFrame(data,index=["Student1","Student2","Student3","Student4"])
print(df)

              Name  Age  Marks
Student1     Aftab   20    100
Student2   Ghaffar   18     80
Student3    Arslan   22     85
Student4  Abdullah   21     95

In [16]:
print(df.loc["Student1"])

Name     Aftab
Age         20
Marks      100
Name: Student1, dtype: object

In [26]:
import pandas as pd
df=pd.read_excel("C:\\Users\\N TEACH\\Macine laening\\Pandas\\Aftab.csv.xlsx")
print(df)

       Name  Age  Marks
0     Aftab   20    100
1   Ghaffar   18     80
2    Arslan   22     85
3  Abdullah   21     95

In [31]:
import pandas as pd
df=pd.read_excel(r"C:\Users\N TEACH\Macine laening\Pandas\Aftab.csv.xlsx")
print(df)

       Name  Age  Marks
0     Aftab   20    100
1   Ghaffar   18     80
2    Arslan   22     85
3  Abdullah   21     95

In [29]:
import pandas as pd
df=pd.read_excel("C:/Users/N TEACH/Macine laening/Pandas/Aftab.csv.xlsx")
print(df)

       Name  Age  Marks
0     Aftab   20    100
1   Ghaffar   18     80
2    Arslan   22     85
3  Abdullah   21     95

# Basic Operations of DataFrame

In [37]:
print("First 2 rows")
print(df.head(2))
print("\nColumns")
print(df.columns)
print("\nStatetics")
print(df.describe())

First 2 rows
      Name  Age  Marks
0    Aftab   20    100
1  Ghaffar   18     80

Columns
Index(['Name', 'Age', 'Marks'], dtype='object')

Statetics
             Age       Marks
count   4.000000    4.000000
mean   20.250000   90.000000
std     1.707825    9.128709
min    18.000000   80.000000
25%    19.500000   83.750000
50%    20.500000   90.000000
75%    21.250000   96.250000
max    22.000000  100.000000

# Data Cleaning

In [41]:
# Bad data could be:

# Empty cells
# Data in wrong format
# Wrong data
# Duplicates

In [40]:
#DataSet with Missing Values
import pandas as pd
import numpy as np
data={
    "Name":["Aftab",None,"Arslan","Abdullah"],
    "Age":[20,18,np.nan,21],
    "Marks":[20,np.nan,85,95]
    
}
df=pd.DataFrame(data)
print(df)

       Name   Age  Marks
0     Aftab  20.0   20.0
1      None  18.0    NaN
2    Arslan   NaN   85.0
3  Abdullah  21.0   95.0

In [47]:
# Checkin Missing Values
print(df.isnull())

    Name    Age  Marks
0  False  False  False
1   True  False   True
2  False   True  False
3  False  False  False

In [49]:
# Count Missig values in each column
print(df.isnull().sum())

Name     1
Age      1
Marks    1
dtype: int64

In [50]:
# Remove Missing Values
clean_df=df.dropna()
print(clean_df.to_string())

       Name   Age  Marks
0     Aftab  20.0   20.0
3  Abdullah  21.0   95.0

In [51]:
#DataSet with Missing Values
import pandas as pd
import numpy as np
data={
    "Name":["Aftab",None,"Arslan","Abdullah"],
    "Age":[20,18,np.nan,21],
    "Marks":[20,np.nan,85,95]
    
}
df=pd.DataFrame(data)
print(df)

       Name   Age  Marks
0     Aftab  20.0   20.0
1      None  18.0    NaN
2    Arslan   NaN   85.0
3  Abdullah  21.0   95.0

In [53]:
print(df.isnull())

    Name    Age  Marks
0  False  False  False
1   True  False   True
2  False   True  False
3  False  False  False

In [55]:
new_data=df.dropna(inplace=True)
print(new_data)

None

In [56]:
print(df)

       Name   Age  Marks
0     Aftab  20.0   20.0
3  Abdullah  21.0   95.0

In [57]:
#DataSet with Missing Values
import pandas as pd
import numpy as np
data={
    "Name":["Aftab",None,"Arslan","Abdullah"],
    "Age":[20,18,np.nan,21],
    "Marks":[20,np.nan,85,95]
    
}
df=pd.DataFrame(data)
print(df)

       Name   Age  Marks
0     Aftab  20.0   20.0
1      None  18.0    NaN
2    Arslan   NaN   85.0
3  Abdullah  21.0   95.0

In [58]:
print(df.fillna(95,inplace=True))

None

In [59]:
df

       Name   Age  Marks
0     Aftab  20.0   20.0
1        95  18.0   95.0
2    Arslan  95.0   85.0
3  Abdullah  21.0   95.0

In [60]:
#DataSet with Missing Values
import pandas as pd
import numpy as np
data={
    "Name":["Aftab",None,"Arslan","Abdullah"],
    "Age":[20,18,np.nan,21],
    "Marks":[20,np.nan,85,95]
    
}
df=pd.DataFrame(data)
print(df)

       Name   Age  Marks
0     Aftab  20.0   20.0
1      None  18.0    NaN
2    Arslan   NaN   85.0
3  Abdullah  21.0   95.0

In [63]:
print(df.fillna({"Marks":95},inplace=True))

None

In [64]:
df

       Name   Age  Marks
0     Aftab  20.0   20.0
1      None  18.0   95.0
2    Arslan   NaN   85.0
3  Abdullah  21.0   95.0

In [65]:
print(df.fillna({"Name":"Ghaffar"}, inplace=True))

None

In [67]:
print(df)

       Name   Age  Marks
0     Aftab  20.0   20.0
1   Ghaffar  18.0   95.0
2    Arslan   NaN   85.0
3  Abdullah  21.0   95.0

In [97]:
x=df["Age"].mean()
df.fillna({"Age":x},inplace=True)
print(df)

       Name    Age  Marks
0     Aftab  20.00   20.0
1     Aftab  18.00    NaN
2    Arslan  19.75   85.0
3  Abdullah  21.00   95.0
4     Aftab  20.00   20.0

In [72]:
x

19.666666666666668

In [73]:
df

       Name        Age  Marks
0     Aftab  20.000000   20.0
1   Ghaffar  18.000000   95.0
2    Arslan  19.666667   85.0
3  Abdullah  21.000000   95.0

In [98]:
#DataSet with Missing Values
import pandas as pd
import numpy as np
data={
    "Name":["Aftab",None,"Arslan","Abdullah","Aftab"],
    "Age":[20,18,np.nan,21,20],
    "Marks":[20,np.nan,85,95,20]
    
}
df=pd.DataFrame(data)
print("Before filling")
print(df)

Before filling
       Name   Age  Marks
0     Aftab  20.0   20.0
1      None  18.0    NaN
2    Arslan   NaN   85.0
3  Abdullah  21.0   95.0
4     Aftab  20.0   20.0

In [99]:
print("After Filling Data")
x=df["Name"].mode()[0]
df.fillna({"Name":x},inplace=True)
print(df)

After Filling Data
       Name   Age  Marks
0     Aftab  20.0   20.0
1     Aftab  18.0    NaN
2    Arslan   NaN   85.0
3  Abdullah  21.0   95.0
4     Aftab  20.0   20.0

In [100]:
print("Mode Name: ", x)

Mode Name:  Aftab

In [101]:
x=df["Age"].median()
df.fillna({"Age":x},inplace=True)
print(df)

       Name   Age  Marks
0     Aftab  20.0   20.0
1     Aftab  18.0    NaN
2    Arslan  20.0   85.0
3  Abdullah  21.0   95.0
4     Aftab  20.0   20.0

In [102]:
print(x)

20.0

In [107]:
new_df=df.drop_duplicates()
print("Cleaned data: ")
print(new_df)

Cleaned data:
       Name   Age  Marks
0     Aftab  20.0   20.0
1     Aftab  18.0    NaN
2    Arslan  20.0   85.0
3  Abdullah  21.0   95.0

In [125]:
# Data in Wrong Formate

In [127]:
import pandas as pd
data={
    "Name":["Aftab","Arslan","Abdullah","Ghaffar"],
    "Date":["2026-06-20","21/06/2026","Jun 23, 2026","2026.06.22"],
    "Marks":[100,85,95,80]
}


df=pd.DataFrame(data)

df["Date"]=pd.to_datetime(df["Date"],format="mixed")

print(df.to_string())

       Name       Date  Marks
0     Aftab 2026-06-20    100
1    Arslan 2026-06-21     85
2  Abdullah 2026-06-23     95
3   Ghaffar 2026-06-22     80